export const localData = [
  {
    id: 14,
    type: "deals",
    image: "images/601-Combo 1.png",
    name: "Hot Twister Box",
    description: "Red Hot twister Sandwich + Fries+ Drink + Coleslaw + 1 COB",
    price: "28 QAR",
  },
  {
    id: 15,
    type: "forSharing",
    image: "images/img_469combo1.png",
    name: "Red Hot Duo",
    description: "2 Red Hot Twisters + Fries + Drink Can",
    price: "26 QAR",
  },
  {
    id: 16,
    type: "forOne",
    image: "images/img_469combo1.png",
    name: "Red Hot Twister Meal",
    description: "Red hot twister + Fries + Drink",
    price: "20 QAR",
  },
  {
    id: 17,
    type: "sidesDesserts",
    image: "images/img_469combo1.png",
    name: "Smokin' Cheesy Combo",
    description: "Smokin' Cheesy Burger + Dippers Fries + Drink",
    price: "35 QAR",
  },
  {
    id: 18,
    type: "favorites",
    image: "images/img_469combo1.png",
    name: "Zinger + Twister Meal",
    description: "Zinger + Twister + fries + Pepsi",
    price: "26 QAR",
  },
  {
    id: 19,
    type: "deals",
    image: "images/img_571combo1.png",
    name: "Deluxe Burger Combo",
    description: "Deluxe Burger + Large Fries + Shake",
    price: "30 QAR",
  },
  {
    id: 20,
    type: "forSharing",
    image: "images/img_456combo1.png",
    name: "Family Feast",
    description: "Family-sized Chicken Bucket + Sides + Drinks",
    price: "50 QAR",
  },
  {
    id: 21,
    type: "forOne",
    image: "images/img_593combo1.png",
    name: "Spicy Chicken Wrap",
    description: "Spicy Chicken Wrap + Medium Fries + Soda",
    price: "18 QAR",
  },
  {
    id: 22,
    type: "sidesDesserts",
    image: "images/img_117combo1.png",
    name: "Chocolate Lava Cake",
    description: "Decadent Chocolate Cake with Molten Center",
    price: "12 QAR",
  },
  {
    id: 32,
    type: "sidesDesserts",
    image: "images/img_117combo1.png",
    name: "Fruit Salad Bowl",
    description: "Fresh Fruit Salad Bowl with Honey-Lime Dressing",
    price: "15 QAR",
  },
  {
    id: 24,
    type: "beverages",
    image: "images/img_618combo1.png",
    name: "Refreshing Lemonade",
    description: "Chilled Lemonade with a hint of mint",
    price: "8 QAR",
  },
  {
    id: 25,
    type: "beverages",
    image: "images/img_619combo1.png",
    name: "Iced Caramel Macchiato",
    description: "Smooth Iced Caramel Macchiato with whipped cream",
    price: "12 QAR",
  },
  {
    id: 26,
    type: "sandwiches",
    image: "images/img_505combo1.png",
    name: "Grilled Chicken Club",
    description: "Grilled Chicken, Bacon, Lettuce, and Tomato",
    price: "22 QAR",
  },
  {
    id: 27,
    type: "sandwiches",
    image: "images/img_606combo1.png",
    name: "Vegetarian Delight",
    description: "Delicious Veggie Sandwich with Avocado",
    price: "18 QAR",
  },
  {
    id: 28,
    type: "favorites",
    image: "images/img_707combo1.png",
    name: "Chef's Special Platter",
    description: "Chef's selection of the day's best dishes",
    price: "40 QAR",
  },
  {
    id: 29,
    type: "favorites",
    image: "images/img_808combo1.png",
    name: "Seafood Extravaganza",
    description: "Assorted Seafood Platter with Dipping Sauces",
    price: "55 QAR",
  },
  {
    id: 30,
    type: "deals",
    image: "images/img_619combo1.png",
    name: "Ultimate Combo Feast",
    description: "A combination of our best-selling items",
    price: "48 QAR",
  },
  {
    id: 31,
    type: "beverages",
    image: "images/img_010combo1.png",
    name: "Mango Tango Smoothie",
    description: "Smooth Mango Tango Smoothie with a tropical twist",
    price: "10 QAR",
  },
  {
    id: 32,
    type: "sandwiches",
    image: "images/img_111combo1.png",
    name: "BBQ Pulled Pork Sandwich",
    description: "Savory BBQ Pulled Pork on a Soft Bun",
    price: "25 QAR",
  },
  {
    id: 33,
    type: "forOne",
    image: "images/img_212combo1.png",
    name: "Classic Cheeseburger Meal",
    description: "Classic Cheeseburger + Fries + Cola",
    price: "24 QAR",
  },
];
